# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f59b0e49a0e93b9409ad005e4b7e2eef58ece3b5ce85192050b5bad3822f6a27e474957250505fa6243b8b75b3037a096e154ca4e1b94d3d832a99dcf433aa2

test:
  secret_key_base: 78ae342f5160489513744f1519fb8def5a5d05a02c5cbcbb034d9a7c77034b1076a9427c9f7cba3b569df90b741c2de0175b9a867dc78b7790e73a999768b243

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
